### ISSUE TITLE
GO 和END_TOKEN？

### ISSUE THREAD

**Issue by Lanme** [chenjun2hao/Attention_ocr.pytorch#19]
这里面训练有加GO(START_TOKEN)和END_TOKEN么？我只在crnn.lang中看到target_txt_decode有加，但是这个函数没有被调用到。
data = val_iter.next()
cpu_images, cpu_texts = data
...
target_variable = converter.encode(cpu_texts)
target_variable = target_variable.cuda()
decoder_input = target_variable[0].cuda()
这里decoder_input val的decode_input(no_teach_forcing)应该是一个GO(START_TOKEN)，看上去它调用的是一个cpu_texts的第一个字吧?

**Comment by chenjun2hao** [comment]
GO和END_TOKEN是编码到训练所需要用到的序列中的。可以多看看paper。

**Comment by Lanme** [comment]
并没有看到这两个token有加进去训练哦
